apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-azure
  template:
    metadata:
      labels:
        app: redis-azure
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: redis
        image: redis:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 6379
  selector:
    app: redis-azure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votingapp-azure
  template:
    metadata:
      labels:
        app: votingapp-azure
      STRESS_SECS: 2
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: alfred-voting
        image: whujin11e/public:azure_voting_app
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "redis"
        - name: STRESS_SECS
          value : "2"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: votingapp-azure