apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votingapp-ingress
  annotations:
    validate.nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: letsencrypt
    cert-manager.io/issuer-kind: Issuer
    cert-manager.io/issuer-group: cert-manager.io
spec:
  ingressClassName: nginx
  rules:
  - host: vote.simplon-duna.space
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: voting-service
            port: 
              number: 80
#  tls: # placing a host in the TLS config will determine what ends up in the cert's subjectAlt
#  - host:
#    - vote.simplon-duna.space
#    secretname: secret-tls # cert-manager will store the created certificate in this secret.
